Para o problema de caminho mínimo o algoritmo de dijkstra deve possuir os seguintes parâmetros:
-h : mostra o help
-o <arquivo> : redireciona a saida para o ‘‘arquivo’’
-f <arquivo> : indica o ‘‘arquivo’’ que contém o grafo de entrada
-i : vértice inicial

Exemplos de execução:
Imprime a distância do vértice inicial 1 até os demais
$ ./djikstra -f arquivo-entrada.dat -i 1
1:0 2:3 3:4 4:2 5:10 6:3
